# Generated by Django 4.2.3 on 2023-08-03 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name': 'survey', 'verbose_name_plural': 'surveys'},
        ),
        migrations.RemoveField(
            model_name='survey',
            name='sruvey_name',
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(default='empty'),
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=60)),
                ('question', models.TextField(default='empty')),
                ('question_type', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.survey', to_field='survey_name')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('POS', 'POSITIVE'), ('NEG', 'NEGATIVE')], default='NEG', max_length=3)),
                ('question', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='survey.questions')),
                ('survey_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey', to_field='survey_name')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'question')},
            },
        ),
    ]
