# Generated by Django 4.2.3 on 2023-07-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0002_questions_responses"),
    ]

    operations = [
        migrations.AddField(
            model_name="responses", name="user_id", field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="responses",
            name="response",
            field=models.JSONField(default=dict),
        ),
    ]
